# --- Development Configuration ---

# Database (Local/Docker Compose)
spring.datasource.url=jdbc:postgresql://localhost:15432/monsplitdb
spring.datasource.username=user
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Vaadin Development
vaadin.launch-browser=false
vaadin.devmode-caching=false
vaadin.frontend.hotdeploy=true

# Logging
logging.level.root=INFO
logging.level.dev.iamkavindu.monsplit=DEBUG
logging.level.org.springframework.security=DEBUG
