# --- Common Configuration ---

# Application
spring.application.name=monsplit
server.port=8080

# JPA
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Vaadin Common
vaadin.url-mapping=/monsplit/*
vaadin.react.enable=false

# Default Profile (Active by default if not specified)
# spring.profiles.active=dev
